name: CD Omnamah....

on: pull_request

concurrency:
  group: Deployments
  
jobs:
  build-main: 
     runs-on: ubuntu-latest
     if: ${{ github.event.pull_request.merged == true && (github.event_name == 'pull_request' && github.ref == 'refs/heads/main') }}
     
     steps:
      - name: sample-run
        run: echo Hi
